### ISSUE TITLE
Training from scratch - unrecognized arguments

### ISSUE THREAD

**Issue by WinkelsK** [bzhanglab/AutoRT#15]
Hello again :)
The transfer learing example is now running. But as I have other modifications in my dataset I need to train from scratch. Whenn running the "from scartch" example it gives me the following error. Apparently "-p" and "-l" are not defined..
~~~
(base) C:\AutoRT-master\example>python ../autort.py train -e 100 -b 64 -g ../mod
els/base_model/model.json -u m -p 1 -i data/PXD006109_Cerebellum_rt_add_mox_all_
rt_range_3_train.tsv -sm min_max -l 48 -rlr -n 20 -o PXD006109_models/
2021-10-20 13:57:06.249560: W tensorflow/stream_executor/platform/default/dso_lo
ader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64
_110.dll not found
2021-10-20 13:57:06.254561: I tensorflow/stream_executor/cuda/cudart_stub.cc:29]
 Ignore above cudart dlerror if you do not have a GPU set up on your machine.
usage: autort.py [-h] -i INPUT [-o OUT_DIR] [-e EPOCHS] [-b BATCH_SIZE]
                 [-r2 MAX_RT] [-u UNIT] [-sm SCALE_METHOD] [-sf SCALE_FACTOR]
                 [-m MODEL_FILE] [-r] [-n EARLY_STOP_PATIENCE] [-rlr] [-g GPU]
                 [-d] [-f OUTLIER_RATIO]
autort.py: error: unrecognized arguments: -p 1 -l 48

**Comment by wenbostar** [comment]
You don’t need to set -l and -p anymore using the latest version of AutoRT. The general base model can support up to 5 modifications and the max length of peptides is 60. You just need to use 2 to encode dimethylated lysine and 3 to encode nterm acetylation. We already use 1 to encode oxidation of M. You can still use the example transfer learning script for training.
