### ISSUE TITLE
Training From Scratch Crashing

### ISSUE THREAD

**Issue by bertauchekurtis** [bzhanglab/AutoRT#17]
Hello. I'm trying to train a model from scratch but I'm unable to run Auto RT. Every time I try to train the model I receive the following error, and I'm not sure what to do about it. Thanks. :)

> C:\Users\Kurtis\Desktop\Research\AutoRT-master>py autort.py train -i C:\Users\Kurtis\Desktop\Research\data\autoRTTrainingSet.tsv -o C:\Users\Kurtis\Desktop\Research\data
> Scaling method: min_max
> Step 1:
> 
> Traceback (most recent call last):
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort.py", line 158, in <module>
>     main()
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort.py", line 109, in main
>     two_step_ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=batch_size,
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort\RTModels.py", line 675, in two_step_ensemble_models
>     ensemble_models(models_file=models_file, input_data=input_data, ensemble_method=ensemble_method,
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort\RTModels.py", line 735, in ensemble_models
>     with open(models_file, "r") as read_file:
> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by wenbostar** [comment]
You have to specify the model file path:

```sh
py autort.py train -e 100 -b 64 -g models/base_model/model.json -u m -i C:\Users\Kurtis\Desktop\Research\data\autoRTTrainingSet.tsv -sm min_max -rlr -n 20 -o C:\Users\Kurtis\Desktop\Research\data
```
What type of variable modifications does your training data contain? If there are only variable modifications from the list below, I highly recommend you to use our pre-trained models with transfer learning. This could significantly increase RT prediction performance compared with training a model from scratch.
```
Oxidation (M), Phosphorylation (STY), Acetylation (K), Ubiquitination (K).
```

**Comment by bertauchekurtis** [comment]
Ah, I see. Thank you so much for the very fast explanation! I am only using Oxidation (M) and Phosphorylation (STY), so I will look into the transfer learning. Thank you.

**Comment by bertauchekurtis** [comment]
Actually, I am still having the same issue even when specifiying the model file path:

> 
> C:\Users\Kurtis\Desktop\Research\AutoRT-master>py autort.py train -e 100 -b 64 -g models/base_model/model.json -u m -i C:\Users\Kurtis\Desktop\Research\data\autoRTTrainingSet.tsv -sm min_max -rlr -n 20 -o C:\Users\Kurtis\Desktop\Research\data
> Scaling method: min_max
> Step 1:
> 
> Traceback (most recent call last):
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort.py", line 158, in <module>
>     main()
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort.py", line 109, in main
>     two_step_ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=batch_size,
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort\RTModels.py", line 675, in two_step_ensemble_models
>     ensemble_models(models_file=models_file, input_data=input_data, ensemble_method=ensemble_method,
>   File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort\RTModels.py", line 735, in ensemble_models
>     with open(models_file, "r") as read_file:
> TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by wenbostar** [comment]
We have pre-trained phosphorylation base model, so you could use the following command line to train your model with transfer learning strategy:

```sh
py autort.py train -i C:\Users\Kurtis\Desktop\Research\data\autoRTTrainingSet.tsv -o C:\Users\Kurtis\Desktop\Research\data\tf_model/ -e 40 -b 64 -u m -m models/ptm_base_model/phosphorylation_sty/model.json -rlr -n 10
```

Please note you have to use "1" to replace oxidated M, "2" to replace phosphorylated S, "3" to replace phosphorylated T and "4" to replace phosphorylated Y in your training data (C:\Users\Kurtis\Desktop\Research\data\autoRTTrainingSet.tsv) as described at https://github.com/bzhanglab/AutoRT#usage. Don't need to change unmodified M, S, T and Y in your training data.

**Comment by wenbostar** [comment]
> Actually, I am still having the same issue even when specifiying the model file path:
> 
> > C:\Users\Kurtis\Desktop\Research\AutoRT-master>py autort.py train -e 100 -b 64 -g models/base_model/model.json -u m -i C:\Users\Kurtis\Desktop\Research\data\autoRTTrainingSet.tsv -sm min_max -rlr -n 20 -o C:\Users\Kurtis\Desktop\Research\data
> > Scaling method: min_max
> > Step 1:
> > Traceback (most recent call last):
> > File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort.py", line 158, in 
> > main()
> > File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort.py", line 109, in main
> > two_step_ensemble_models(input_data=input_file, nb_epoch=epochs, batch_size=batch_size,
> > File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort\RTModels.py", line 675, in two_step_ensemble_models
> > ensemble_models(models_file=models_file, input_data=input_data, ensemble_method=ensemble_method,
> > File "C:\Users\Kurtis\Desktop\Research\AutoRT-master\autort\RTModels.py", line 735, in ensemble_models
> > with open(models_file, "r") as read_file:
> > TypeError: expected str, bytes or os.PathLike object, not NoneType

Sorry, there was a typo in the command line. Please use the new command line as shown above.

**Comment by bertauchekurtis** [comment]
It is working now. Thank you very much for your help and showing me what I was doing wrong. :)

**Comment by wenbostar** [comment]
You're welcome. AutoRT could predict RT for phosphopeptides very accurately. If the prediction performance is not as good as shown at https://github.com/bzhanglab/AutoRT#performance-of-autort, please let me know. I'm happy to help.

**Comment by bertauchekurtis** [comment]
One more question if you don't mind. Once I've finished the training, which model file should I be using when I run the predictions?

**Comment by wenbostar** [comment]
Below please find the command line for prediction. The output folder **C:\Users\Kurtis\Desktop\Research\data\tf_model** contains the trained model files and you only need to give **C:\Users\Kurtis\Desktop\Research\data\tf_model\model.json** to -s which contains all the model information needed in prediction.
```sh
py autort.py predict -t test.tsv -s C:\Users\Kurtis\Desktop\Research\data\tf_model\model.json -o tf_prediction/ -p test
```

**Comment by bertauchekurtis** [comment]
Okay, thank you!

**Comment by bertauchekurtis** [comment]
What effect do the batch size and epoch size parameters have on the training of the model?

**Comment by wenbostar** [comment]
The two parameters may have a big impact on the performance. You could use "-e 40 -b 64". I used this on many datasets from small size (~1000 peptides) to very large size and it works very well.

**Comment by bertauchekurtis** [comment]
Okay, I will try that, thank you. My dataset has about ~70,000 peptides.

**Comment by wenbostar** [comment]
The size is large enough to train a very good model. If the dataset was generated from multiple MS/MS runs/fractions, make sure that the RTs of peptides from different runs/fractions are well aligned. In addition, for each peptide (peptide + modification, peptide form) only keep one entry in the training dataset.
