### ISSUE TITLE
training with transfer learning

### ISSUE THREAD

**Issue by apataskar** [bzhanglab/AutoRT#18]
Hi Bo,

I have a question about training using transfer learning.  How did you select which peptides are in (-t 28CPTAC_COprospective_W_VU_20150810_05CO037_f01_normal_test.tsv) files. Are these only variant peptides or all-peptides (or is there any other kind of selection). I want to generate training data for transfer learning and wonder what is the best strategy?

Looking forward to hearing from you.
Best

Abhi

**Comment by wenbostar** [comment]
Hi Abhi,

For training data, you could use all confidently identified known peptides (e.g., the peptides passed 1% FDR). You could also leave a small fraction (such as 10%) of the known peptides as testing data. Based on the testing data, you will know the performance of the RT prediction model. After you have the trained model with transfer learning, you will be able to predict RT for any novel peptides with this model.

Bo

**Comment by apataskar** [comment]
Great Thanks Bo! One more question- can I take average of retention times for a peptide across multiple TMT experiment or does it have to be only per TMT experiment?

Abhi

On May 23, 2022, at 5:53 PM, Bo ***@***.******@***.***>> wrote:



Hi Abhi,

For training data, you could use all confidently identified known peptides (e.g., the peptides passed 1% FDR). You could also leave a small fraction (such as 10%) of the known peptides as testing data. Based on the testing data, you will know the performance of the RT prediction model. After you have the trained model with transfer learning, you will be able to predict RT for any novel peptides with this model.

Bo

**Comment by apataskar** [comment]
And in the prediction, also the novel peptides have to be separated into where (which experiment/sample) they originate from?



From: Abhijeet Pataskar
Sent: dinsdag 24 mei 2022 16:26
To: 'bzhanglab/AutoRT' ***@***.***>; bzhanglab/AutoRT ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [bzhanglab/AutoRT] training transfer_learning (Issue #18)

Understand. Does that mean fractionation may also have RT drift?

**Comment by wenbostar** [comment]
> Understand. Does that mean fractionation may also have RT drift?

It's possible. We observed this in quite a few datasets.

**Comment by apataskar** [comment]
Sorry seconds

From: Abhijeet Pataskar
Sent: dinsdag 24 mei 2022 17:31
To: 'bzhanglab/AutoRT' ***@***.***>; bzhanglab/AutoRT ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [bzhanglab/AutoRT] training transfer_learning (Issue #18)


Great final question (for now )

Are the parameters okay?

python3 ../autort.py train -i data/final_01CPTAC_f01.txt.txt -o dir_01CPTAC_f01.txt.txt -e 40 -b 64 -u s -m ../models/general_base_model/model.json -rlr -n 10

my retention times are in minutes

**Comment by wenbostar** [comment]
> python3 ../autort.py train -i data/final_01CPTAC_f01.txt.txt -o dir_01CPTAC_f01.txt.txt -e 40 -b 64 -u s -m ../models/general_base_model/model.json -rlr -n 10

Since the unit of RT is in minute, "-u" should be set as "-u m". In addition, make sure modifications are coded in the right way. I'm happy to help check that if you need.

**Comment by wenbostar** [comment]
> I changed modification M-oxi to 1 (omitted M and wrote 1) and omitted all fixed modifications.

It looks the unit of RT is in second. You could use "-u s" or convert the RT to minute and then use "-u m".

**Comment by wenbostar** [comment]
@apataskar , does AutoRT work well in your analysis? I will close this issue if you don't have any additional questions about this issue.

**Comment by apataskar** [comment]
Yes! Its works really as expected. Yes, I will contact again if I get stuck somewhere ☺

Thanks a lot
