### ISSUE TITLE
The range of retention time for a peptide of length 8aa to 32aa 

### ISSUE THREAD

**Issue by szhao-amunix** [bzhanglab/AutoRT#19]
The RT in the training set of AutoRT ranges from 0 to 100 . I believe this should be true for most peptides.

I need to design a peptide library (in which each has 8aa to 30aa) and want to predict RT for individual peptide using AutoRT. Ideally, the distribution of RTs is close to 'uniform'.  

I don't want to retrain the model. Instead I prefer to use the out-of-box model from AutoRT. But I have a concern on those peptides in my library:  what’s the chance of a peptide having **RT >100**?

**Comment by wenbostar** [comment]
If you use this model: https://github.com/bzhanglab/AutoRT/blob/master/models/general_base_model/model.json, I think you will not have peptides with predicted RTs > 101.33 which is the max RT in the training data.

**Comment by szhao-amunix** [comment]
Thank you for clarification.
