### ISSUE TITLE
Question: TMT model included?

### ISSUE THREAD

**Issue by courcelm** [bzhanglab/AutoRT#3]
Hello,

Doest AutoRT includes TMT models?

Thanks.

**Comment by wenbostar** [comment]
Yes. The model which is available in the Github supports TMT data.

**Comment by courcelm** [comment]
How do I name the TMT modification?

**Comment by wenbostar** [comment]
TMT modifications are all fixed modifications, so you don't need to consider them in the model as we use the transfer learning strategy. You only need to encode variable modifications as described in the [README](https://github.com/bzhanglab/AutoRT).

**Comment by wenbostar** [comment]
Please reopen this issue if you still have questions about it.
