### ISSUE TITLE
Upgradation of script to tensorflow >= 2 version?

### ISSUE THREAD

**Issue by chinmayaNK** [bzhanglab/AutoRT#5]
Hello,

Is it possible to upgrade the AutoRT scripts to TensorFlow 2.2.0 or above versions?

Currently, I am using TensorFlow 2.2.0 and I am not able to install any older versions of TensorFlow <=1.15.

Thanks & Regards,
Chinmaya

**Comment by wenbostar** [comment]
We do have a plan to update AutoRT to TensorFlow 2.x. But it may take a few months since we have to reconstruct and retrain the base models. 

You could also try to use AutoRT docker at this time.
```
docker pull proteomics/autort
```

**Comment by wenbostar** [comment]
I have updated AutoRT to support TensorFlow 2.x (2.3.1).

**Comment by chinmayaNK22** [comment]
Thanks a lot wenbostar.
I will try to run the tool in my system and will let you if any issues arise.
