### ISSUE TITLE
Peptide lengths don't seem to be properly checked during transfer learning

### ISSUE THREAD

**Issue by ebzheng** [bzhanglab/AutoRT#7]
I'm using transfer learning on a dataset that apparently contains some fairly long potential peptide identifications. In some runs, a 53 residue peptide was identified (and is thus in my training set), and in these runs, I get a ValueError thrown:

<details>

```
Scaling method: min_max
Transfer learning ...

Deep learning model: 0
Load aa coding data from file models/base_models_PXD006109/aa.tsv
AA types: 21
Longest peptide in training data: 53

['1', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y']
RT range: 0 - 285

X_train shape:
(33617, 53, 21)
X_test shape:
(3736, 53, 21)
Modeling start ...
48
Perform transfer learning ...
The number of layers: 22
<keras.optimizers.Adam object at 0x7f632c654ed0>
Use optimizer: Adam from saved model
Used optimizer:
<keras.optimizers.Adam object at 0x7f632c693c10>
{'scaling_method': 'min_max', 'rt_max': 285.92, 'rt_min': 0.0}
Use ReduceLROnPlateau!
Use EarlyStopping: 10
Traceback (most recent call last):
  File "autort.py", line 133, in <module>
    main()
  File "autort.py", line 99, in main
    add_reverse=add_reverse,add_ReduceLROnPlateau=add_ReduceLROnPlateau)
  File "/rugpfs/fs0/home/ezheng/src/AutoRT/autort/RTModels.py", line 471, in ensemble_models
    callbacks=all_callbacks)#, keras.callbacks.ReduceLROnPlateau(patience=3, factor=0.5, verbose=1, min_lr=0.000001)])
  File "/ru-auth/local/home/ezheng/miniconda3/envs/autoRT/lib/python3.7/site-packages/keras/engine/training.py", line 952, in fit
    batch_size=batch_size)
  File "/ru-auth/local/home/ezheng/miniconda3/envs/autoRT/lib/python3.7/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/ru-auth/local/home/ezheng/miniconda3/envs/autoRT/lib/python3.7/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected conv1d_1_input to have shape (48, 21) but got array with shape (53, 21)
```

</details>

By inference and reviewing the source code, I suspect that 48 is the longest peptide that the PXD006109 model was trained on, and my training set of course has longest length 53. However, I'm surprised that the checks for length mismatch aren't firing (since I could pretty easily just exclude the long peptide):

https://github.com/bzhanglab/AutoRT/blob/e04a42cf51c1053719d1c2f10680a18788c76396/autort/RTModels.py#L394-L404

I'm happy to provide sample data privately if you need it to reproduce.

**Comment by wenbostar** [comment]
Thanks for your interest in AutoRT. For transfer learning, the maximum length of peptides in the training data must be <= 48 which is either the length of the longest peptide in the training data used to train the base models or the number given to parameter "-l" when training the base models. In general, we should only have very few peptides with length greater than 48. You could remove the peptides with length > 48 from your training data or retrain the base models (not transfer learning step) by setting "-l 53". 

```sh
cd example
## training
python ../autort.py train -e 100 -b 64 -g ../models/base_models/model.json -u m -p 1 -i data/PXD006109_Cerebellum_rt_add_mox_all_rt_range_3_train.tsv -sm min_max -l 53 -rlr -n 20 -o PXD006109_models/
```

I can also provide you the trained based models that support peptides with length > 48 if it helps.

**Comment by ebzheng** [comment]
Thanks for responding! Yes, I understand the maximum length requirements for transfer learning now -- I'm just opening the issue to let you know that the designed feedback (L394-404) doesn't seem to be happening. That is, my logs don't show any messages like "The max length (XXX) in the training data should be less than the length supported by the model." I figured it out relatively quickly, but I anticipate that not every user will be.

(A tangent -- for transfer learning, is the correct usage to train a model per each LC-MS/MS run and not for an aggregate of several runs?)

**Comment by wenbostar** [comment]
This is a good point. I just updated the readme to remind users about the length issue in transfer learning step.

> (A tangent -- for transfer learning, is the correct usage to train a model per each LC-MS/MS run and not for an aggregate of several runs?)

Before I combine data from multiple runs for a single training, I always check the RTs of the same peptides from different runs to see if they are very similar. If they are very similar, then there is no problem to combine the data from multiple runs to train a single model. Otherwise, train a model for each run.

**Comment by wenbostar** [comment]
I also updated the code. It will print a message about the peptide length issue if it's not matched between the model and the input data.

**Comment by wenbostar** [comment]
Please reopen this issue if you still have related questions.
